# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78a25a16e01dfcfc2656116cbd8c738eb912060751d81b8002d8abe92df15f43ae9822eb48a954fe09c1fdcd6f8a9bf702c0b811a9427773fa4d80d13db5071

test:
  secret_key_base: 99686c6be370375fd6a467aa7f6820f94a2f38dea2dd1b82fc828b14e70463ca51c9f3d94d9a514e60561128aa7fa7844070cdf9abd5ffe489eb964b9225bd02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
